=== samhuk/exhibitor/src/common/config/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/samhuk/exhibitor/blob/master/src/common/config/schema.json",
  "title": "Exhibitor Config",
  "description": "Config for the Exhibitor CLI",
  "type": "object",
  "properties": {
    "include": {
      "description": "Optional list of glob patterns to select component exhibit files. This is relative to where the config file is. If defined, this must contain at least one entry.",
      "type": "array",
      "minItems": 1,
      "default": ["./**/*.exh.ts", "./**/*.exh.tsx"]
    },
    "exclude": {
      "description": "Optional list of glob patterns to ignore component exhibit files. This is relative to where the config file is.",
      "type": "array",
      "default": []
    },
    "watch": {
      "description": "Optional list of glob patterns to select files/dirs to watch for changes in order to live-reload the exhibitor site. This is relative to where the config file is. If defined, this must contain at least one entry.",
      "type": "array",
      "minItems": 1,
      "default": ["./**/*"]
    },
    "watchExclude": {
      "description": "Optional list of glob patterns to ignore files/dirs to watch for changes in order to live-reload the exhibitor site. This is relative to where the config file is.",
      "type": "array",
      "default": []
    },
    "site": {
      "description": "Optional configuration of the exhibitor site.",
      "type": "object",
      "properties": {
        "title": {
          "description": "Optional title for the browser page of the site.",
          "type": "string",
          "default": "Exhibitor"
        },
        "host": {
          "description": "The host the site will be binded to.",
          "type": "string",
          "default": "localhost"
        },
        "port": {
          "description": "The port the site will be binded to.",
          "type": "number",
          "exclusiveMinimum": 0,
          "exclusiveMaximum": 65535,
          "default": 4001
        }
      }
    },
    "rootStyle": {
      "description": "Optional path to a CSS or SCSS stylesheet to include as a root style. This is useful for defining styles shared by all components, i.e. icon/style libraries like font-awesome, muicons, bootstrap, or your own.",
      "type": "string",
      "deprecated": true
    },
    "rootStyles": {
      "description": "Optional path to a CSS or SCSS stylesheet to include as a root style. This is useful for defining styles shared by all components, i.e. icon/style libraries like font-awesome, muicons, bootstrap, or your own.",
      "type": ["string", "string[]"]
    },
    "verbose": {
      "description": "Enables/disables verbose output for Exhibitor CLI.",
      "type": "boolean"
    },
    "demo": {
      "description": "Optional configuration for the demo deployment (CLI 'demo' command).",
      "type": "object",
      "properties": {
        "outDir": {
          "description": "Directory that the demo deployment files are built to.",
          "type": "string",
          "default": "./.exh/demo"
        },
        "httpPort": {
          "description": "The port the HTTP demo deployment binds to.",
          "exclusiveMinimum": 0,
          "exclusiveMaximum": 65535,
          "type": "number",
          "default": 80
        },
        "enableHttps": {
          "description": "Enables HTTPS functionality for the demo deployment.",
          "type": "boolean",
          "default": false
        },
        "httpsPort": {
          "description": "The port the HTTPS demo deployment binds to.",
          "exclusiveMinimum": 0,
          "exclusiveMaximum": 65535,
          "type": "number",
          "default": 443
        },
        "httpsDomains": {
          "description": "The domains that the HTTPS certificate will be for. This must be defined if demo.enableHttps is true.",
          "type": "array",
          "default": ["example.org"]
        },
        "certDir": {
          "description": "Directory that the certificates for HTTPS functionality will be stored.",
          "type": "string",
          "default": "./certbot"
        }
      }
    }
  }
}

=== samhuk/exhibitor/test/exh.config.json
{
  "$schema": "../src/common/config/schema.json",
  "rootStyles": "../src/ui-component-library/assets/styles/index-dark.scss",
  "include": [
    "./**/*.exh.ts",
    "./**/*.exh.tsx",
    "../src/ui-component-library/**/*.exh.ts",
    "../src/ui-component-library/**/*.exh.tsx"
  ],
  "watch": [
    "./**/*",
    "../src/ui-component-library"
  ],
  "watchExclude": [],
  "site": {
    "port": 4001,
    "title": "Test Component Library"
  },
  "verbose": false
}
